version: '3.8'

services:
  bolt-diy:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    container_name: bolt-diy-production
    ports:
      - "5173:5173"
    env_file:
      - production.env
    environment:
      - NODE_ENV=production
      - VITE_THEME_NAME=sparti
      - RUNNING_IN_DOCKER=true
    volumes:
      # Optional: Mount a volume for persistent data if needed
      - bolt_data:/app/data
      - type: bind
        source: ./Sparti Theme/public/themes/sparti
        target: /app/public/themes/sparti
        read_only: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bolt_network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: bolt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - bolt-diy
    restart: unless-stopped
    networks:
      - bolt_network

volumes:
  bolt_data:
    driver: local

networks:
  bolt_network:
    driver: bridge
