version: '3.8'

services:
  bolt-diy:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    container_name: bolt-diy-production
    ports:
      - "80:5173"
      - "5173:5173"
    env_file:
      - production.env
    environment:
      - NODE_ENV=production
      - VITE_THEME_NAME=sparti
      - RUNNING_IN_DOCKER=true
      - VITE_HMR_HOST=0.0.0.0
    volumes:
      # Optional: Mount a volume for persistent data if needed
      - bolt_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bolt_network

volumes:
  bolt_data:
    driver: local

networks:
  bolt_network:
    driver: bridge
