[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
RUNNING_IN_DOCKER = "true"
VITE_HMR_HOST = "0.0.0.0"
VITE_LOG_LEVEL = "info"
CHOKIDAR_USEPOLLING = "true"
WATCHPACK_POLLING = "true"
FORCE_COLOR = "0"
CI = "true"
HOST = "0.0.0.0"
# Railway will inject PORT at runtime; default to 5173 for local container runs
PORT = "5173"
# Context window default from template (tunable via Railway envs)
DEFAULT_NUM_CTX = "32768"
